# A generic, single database configuration.

[sqlalchemy]
# the value of sqlalchemy.url is looked up in os.environ first then
# as a fallback "alembic_user_defaults" is consulted "alembic.context.config"
# for possible fallback value. If any of these are not present the
# configuration must have sqlalchemy.url defined for sqlalchemy.url
# to be usable for "sqlalchemy.url = driver://user:password@host/dbname"
sqlalchemy.url = sqlite+aiosqlite:///./nano_lab.db


[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
